/* reverse Polish calculator - segmented into separate source files with externs defined in a header file

  On a PC running Windows, EOF via a keyboard can be generated by CTRL-Z

  Changed main to int and added a return value to avoid compiler warnings

    compiled by:
      bcc32c -o ch4-RPN.exe ch4-RPNMain.c ch4-GetOp.c ch4-stack.c ch4-GetCh.c  [ENTER]    

 */

#include <stdio.h>
#include <stdlib.h>
#include "ch4-Calc.h"

#define MAXOP 100    /* max size of operand or operator */
#define NUMBER '0'   /* signal that a number was found */


int main()
{ 
  int type;
  double op2;
  char s[MAXOP];

  while ( (type = getop(s)) != EOF )
  {
    switch(type)
    {
      case NUMBER:
          push(atof(s));
          break;
      case '+':
          push(pop() + pop());
          break;
      case '*':
          push(pop() * pop());
          break;   
      case '-':
          op2 = pop();
          push(pop() - op2);
          break; 
      case '/':
          op2 = pop();
          if ( op2 != 0.0 )  
            push(pop() / op2);
          else  
            printf("error: zero divisor\n"); 
          break;
      case '\n':
          printf("\t%.8g\n", pop()); 
          break;
       default:
          printf("error: unknown command %s\n", s);
          break;
    }
  }

  return (0);
}