/* find all lines matching pattern

  On a PC running Windows, EOF via a keyboard can be generated by CTRL-Z

  Changed main to int and added a return value to avoid compiler warnings. 

    compiled by:
      bcc32c ch4-PatternMatching.c [ENTER]

    PatternMatching < test.txt
    
 */

#include <stdio.h>

#define MAXLINE 1000  /* maximum input line length */

int getline(char s[], int lim);
int strindex(char s[], char t[]);

char pattern[] = "ould";  /* pattern to search for */

int main()
{
  char line[MAXLINE];
  int found = 0;

  while ( getline(line, MAXLINE) > 0 )
    if ( strindex(line, pattern) >= 0 )
    {
      printf("%s", line);
      found++;
    }
    
  return (found);
}


/* getline: get line into s, return length */
int getline(char s[], int lim)
{
  int c, i;

  i = 0;
  while ( --lim > 0 && (c=getchar()) != EOF && c != '\n' )
    s[i++] = c;
  if ( c == '\n')
    s[i++] = c;
  s[i] = '\0';
  return(i);
}


/* strindex: return index of t in s, -1 if none */
int strindex(char s[], char t[])
{
   int i, j, k;

   for ( i = 0; s[i] != '\0'; i++ )
   {
     for ( j=i, k=0; t[k] != '\0' && s[j] == t[k]; j++, k++ )
       ;
     if ( k > 0 && t[k] == '\0' )
       return(i); 
   }
   return(-1);
}