/* rudimentary calculator 

  On a PC running Windows, EOF via a keyboard can be generated by CTRL-Z

  Changed main to int and added a return value to avoid compiler warnings

    compiled by:
      bcc32c ch4-BasicCalculator.c [ENTER]    

 */

#include <stdio.h>
#include <stdlib.h>

#define MAXLINE 1000 /* maximum input line size */

int getline(char s[], int lim);

int main()
{
  double sum;
  char line[MAXLINE];

  sum = 0.0;
  while( getline(line, MAXLINE) > 0 )
    printf("\t%g\n", sum += atof(line));

  return (0);
}


/* getline: read a line into s, return length */
int getline(char s[], int lim)
{
  int c, i;

  for ( i = 0; i < lim-1 && (c = getchar()) != EOF && c != '\n'; ++i ) 
    s[i] = c;

  if ( c == '\n')
  {
     s[i] = c;
     ++i;
  }
  s[i] = '\0';
  return(i);
}


