/* count characters in input; 2nd version

  On a PC running Windows, EOF via a keyboard can be generated by CTRL-Z

   Changed main to int and added a return value to avoid compiler warnings

    compiled by:
      bcc32c ch1-CharCountv2.c [ENTER]

 */

#include <stdio.h>


int main()
{
    double nc;

    nc = 0;
    
    for ( nc = 0; getchar() != EOF; ++nc )
       ;  
    printf("%.0f\n", nc);

    return (0 );
}
