/* copy input to output; 2nd version

  On a PC running Windows, EOL via a keyboard can be generated by CTRL-Z

   Changed main to int and added a return value to avoid compiler warnings

    compiled by:
      bcc32c ch1-CharInputOutputv2.c [ENTER]

 */

#include <stdio.h>


int main()
{
    int c;

    while ( (c = getchar()) != EOF )
       putchar(c);       

    return (0 );
}
