/* count digits, white space, others

  On a PC running Windows, EOF via a keyboard can be generated by CTRL-Z

   Changed main to int and added a return value to avoid compiler warnings

    compiled by:
      bcc32c ch1-ArrayCounter.c [ENTER]

    ch1-ArrayCounter < ch1-ArrayCounter.c
    digits =  10 6 1 1 0 0 0 0 0 1, white space = 232, other = 550

 */

#include <stdio.h>


int main()
{
  int c, i, nwhite, nother;
  int ndigit[10];

  nwhite = nother = 0;
  for (i = 0; i < 10; ++i)
    ndigit[i] = 0;

  while ( (c = getchar()) != EOF )
    if ( c >= '0' && c <= '9')
      ++ndigit[c - '0'];
    else if ( c == ' ' || c == '\n' || c == '\t' )
      ++nwhite;
    else 
      ++nother;

  printf("digits = ");
  for (i = 0; i < 10; ++i)
    printf(" %d", ndigit[i]);
  printf(", white space = %d, other = %d", nwhite, nother);

  return (0);
}
