/* copy input to output; 1st version

  On a PC running Windows, EOL via a keyboard can be generated by CTRL-Z

   Changed main to int and added a return value to avoid compiler warnings

    compiled by:
      bcc32c ch1-CharInputOutputv1.c [ENTER]

 */

#include <stdio.h>


int main()
{
    int c;

    c = getchar();
    while ( c != EOF )
    {
      putchar(c);
      c = getchar();
    }    

    return (0 );
}
